version: '3.1'

services:
  api: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      HOSTNAME: 0.0.0.0
      PORT: 3000
      SECRET: f378b36359c5c12eed9c471d0076a9d8479b8783e1443fb7
      OAUTH_CALLBACK: https://54154e1e.ngrok.io/oauth_callback
      REDIS_URL: redis://redis:6379
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - redis
  redis:
    image: redis
    entrypoint: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    restart: always

volumes:
  redis-data: ~